export const ROLES = {
  CITIZEN: 1,
  COUNCIL_OFFICER: 2,
  FIELD_CREW: 3,
  RELIEF_COORDINATOR: 4,
  SYSTEM_ADMIN: 5,
} as const;

export const INCIDENT_STATUSES = {
  REPORTED: 'REPORTED',
  ANALYZING: 'ANALYZING',
  NEEDS_VERIFICATION: 'NEEDS_VERIFICATION',
  CONFIRMED: 'CONFIRMED',
  DISPATCHED: 'DISPATCHED',
  IN_PROGRESS: 'IN_PROGRESS',
  RESOLVED: 'RESOLVED',
  REJECTED: 'REJECTED',
} as const;

export const TICKET_STATUSES = {
  OPEN: 'OPEN',
  ASSIGNED: 'ASSIGNED',
  ACCEPTED: 'ACCEPTED',
  IN_PROGRESS: 'IN_PROGRESS',
  COMPLETED: 'COMPLETED',
  CLOSED: 'CLOSED',
} as const;

export const CREW_AVAILABILITY = {
  AVAILABLE: 'AVAILABLE',
  BUSY: 'BUSY',
  OFF_DUTY: 'OFF_DUTY',
} as const;

export const HELP_REQUEST_STATUSES = {
  PENDING: 'PENDING',
  ASSIGNED: 'ASSIGNED',
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED',
} as const;

export const SEVERITIES = {
  LOW: 'LOW',
  MEDIUM: 'MEDIUM',
  HIGH: 'HIGH',
  CRITICAL: 'CRITICAL',
} as const;
